test_ackermann_steering_controller:
  ros__parameters:

    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    rear_wheels_names: [re_right_joint, re_left_joint]
    front_wheels_names: [fr_right_joint, fr_left_joint]

    wheelbase: 3.24644
    front_wheel_track: 2.12321
    rear_wheel_track: 1.76868
    front_wheels_radius: 0.45
    rear_wheels_radius: 0.45